"""Retrain, evaluate, and publish the ARRIVA ETA model.

Run from the repository root:

    python3 ml/train.py

The input train/test files must be generated by the Day 1 preprocessing
pipeline. The selected model is published to ml/models/eta_model.pkl.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

import joblib

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from train_eta_models import run_training  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train", default=str(ROOT / "data/processed/train.csv"))
    parser.add_argument("--test", default=str(ROOT / "data/processed/test.csv"))
    parser.add_argument("--model-dir", default=str(ROOT / "ml/models"))
    parser.add_argument("--cv-folds", type=int, default=5)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    model_dir = Path(args.model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)
    report = run_training(
        Path(args.train), Path(args.test), model_dir, cv_folds=args.cv_folds
    )

    source_model = model_dir / "best_eta_model.joblib"
    published_model = model_dir / "eta_model.pkl"
    shutil.copyfile(source_model, published_model)

    bundle = joblib.load(published_model)
    joblib.dump(
        {
            "feature_columns": bundle["feature_columns"],
            "target": bundle["target"],
            "selected_model": bundle["selected_model"],
            "data_source": bundle["data_source"],
        },
        model_dir / "preprocessing.joblib",
    )

    report["published_model"] = str(published_model)
    report["preprocessing_artifact"] = str(model_dir / "preprocessing.joblib")
    (model_dir / "day1_completion.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
