"""Clean and feature-engineer ARRIVA's historical train ETA observations.

The default input is synthetic prototype data generated by
scripts/generate_synthetic_dataset.py. Replace it with a licensed historical
source only after mapping its columns to the documented raw schema.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


RAW_COLUMNS = [
    "record_id",
    "train_id",
    "train_name",
    "service_date",
    "route_id",
    "origin_station",
    "destination_station",
    "section_id",
    "station_sequence",
    "station_name",
    "scheduled_departure",
    "scheduled_arrival",
    "scheduled_destination_arrival",
    "actual_observation_time",
    "actual_destination_arrival",
    "latitude",
    "longitude",
    "current_speed_kmh",
    "distance_remaining_km",
    "current_delay_minutes",
    "station_arrival_time",
    "station_departure_time",
    "weather_condition",
    "track_condition",
    "signal_aspect",
    "historical_section_delay_minutes",
]

DATETIME_COLUMNS = [
    "service_date",
    "scheduled_departure",
    "scheduled_arrival",
    "scheduled_destination_arrival",
    "actual_observation_time",
    "actual_destination_arrival",
    "station_arrival_time",
    "station_departure_time",
]

NUMERIC_COLUMNS = [
    "station_sequence",
    "latitude",
    "longitude",
    "current_speed_kmh",
    "distance_remaining_km",
    "current_delay_minutes",
    "historical_section_delay_minutes",
]

CATEGORICAL_COLUMNS = [
    "train_id",
    "train_name",
    "route_id",
    "origin_station",
    "destination_station",
    "section_id",
    "station_name",
    "weather_condition",
    "track_condition",
    "signal_aspect",
]

FEATURE_COLUMNS = [
    "train_id",
    "route_id",
    "section_id",
    "station_sequence",
    "current_speed_kmh",
    "distance_remaining_km",
    "current_delay_minutes",
    "scheduled_travel_time_min",
    "historical_delay_minutes",
    "station_dwell_time_min",
    "route_section",
    "progress_ratio",
    "observation_hour",
    "day_of_week",
    "weather_condition",
    "track_condition",
    "signal_aspect",
]

TARGET_COLUMN = "target_arrival_delay_minutes"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        default="data/raw/historical_train_observations.csv",
        help="Raw CSV path relative to the repository root.",
    )
    parser.add_argument(
        "--output-dir",
        default="data/processed",
        help="Directory for processed outputs.",
    )
    return parser.parse_args()


def _parse_datetimes(frame: pd.DataFrame) -> pd.DataFrame:
    for column in DATETIME_COLUMNS:
        frame[column] = pd.to_datetime(frame[column], errors="coerce")
    return frame


def _clean(frame: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, int]]:
    summary: dict[str, int] = {"raw_rows": len(frame)}
    frame = frame.copy()
    frame.columns = frame.columns.str.strip()
    missing_columns = sorted(set(RAW_COLUMNS) - set(frame.columns))
    if missing_columns:
        raise ValueError(f"Input is missing required columns: {missing_columns}")
    frame = frame[RAW_COLUMNS]

    before = len(frame)
    frame = frame.drop_duplicates(subset=["record_id", "train_id", "actual_observation_time"])
    summary["duplicate_rows_removed"] = before - len(frame)

    frame = _parse_datetimes(frame)
    summary["invalid_datetime_values"] = int(
        frame[DATETIME_COLUMNS].isna().sum().sum()
    )

    for column in NUMERIC_COLUMNS:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")

    invalid_masks = {
        "invalid_speed_values": (frame["current_speed_kmh"] < 0) | (frame["current_speed_kmh"] > 180),
        "invalid_distance_values": (frame["distance_remaining_km"] < 0) | (frame["distance_remaining_km"] > 5000),
        "invalid_delay_values": (frame["current_delay_minutes"] < -30) | (frame["current_delay_minutes"] > 240),
        "invalid_coordinates": ~frame["latitude"].between(-90, 90) | ~frame["longitude"].between(-180, 180),
    }
    for name, mask in invalid_masks.items():
        summary[name] = int(mask.fillna(False).sum())
        column_map = {
            "invalid_speed_values": "current_speed_kmh",
            "invalid_distance_values": "distance_remaining_km",
            "invalid_delay_values": "current_delay_minutes",
            "invalid_coordinates": "latitude",
        }
        frame.loc[mask, column_map[name]] = pd.NA
        if name == "invalid_coordinates":
            frame.loc[mask, "longitude"] = pd.NA

    frame = frame.dropna(
        subset=[
            "record_id",
            "train_id",
            "route_id",
            "actual_observation_time",
            "actual_destination_arrival",
            "scheduled_departure",
            "scheduled_destination_arrival",
        ]
    )
    summary["rows_removed_for_missing_required_values"] = summary["raw_rows"] - summary["duplicate_rows_removed"] - len(frame)

    for column in NUMERIC_COLUMNS:
        frame[column] = frame[column].fillna(frame.groupby("route_id")[column].transform("median"))
        frame[column] = frame[column].fillna(frame[column].median())
    for column in CATEGORICAL_COLUMNS:
        mode = frame[column].mode(dropna=True)
        frame[column] = frame[column].fillna(mode.iloc[0] if not mode.empty else "unknown")

    # Cap only physically plausible feature outliers; the unmodified target remains auditable.
    speed_outliers = (frame["current_speed_kmh"] > 160) | (frame["current_speed_kmh"] < 5)
    dwell_outliers = frame["station_departure_time"].sub(frame["station_arrival_time"]).dt.total_seconds().div(60).abs() > 45
    summary["reasonable_speed_outliers_capped"] = int(speed_outliers.sum())
    summary["reasonable_dwell_outliers_capped"] = int(dwell_outliers.fillna(False).sum())
    frame["current_speed_kmh"] = frame["current_speed_kmh"].clip(5, 160)
    return frame, summary


def _engineer_features(frame: pd.DataFrame) -> pd.DataFrame:
    engineered = frame.copy()
    engineered["scheduled_travel_time_min"] = (
        engineered["scheduled_destination_arrival"]
        - engineered["scheduled_departure"]
    ).dt.total_seconds().div(60)
    engineered["historical_delay_minutes"] = engineered[
        "historical_section_delay_minutes"
    ]
    engineered["station_dwell_time_min"] = (
        engineered["station_departure_time"]
        - engineered["station_arrival_time"]
    ).dt.total_seconds().div(60)
    engineered["station_dwell_time_min"] = engineered["station_dwell_time_min"].clip(0, 45).fillna(0)
    engineered["route_section"] = (
        engineered["route_id"].astype(str) + ":" + engineered["section_id"].astype(str)
    )
    engineered["observation_hour"] = engineered["actual_observation_time"].dt.hour
    engineered["day_of_week"] = engineered["service_date"].dt.dayofweek
    elapsed_schedule_minutes = (
        engineered["actual_observation_time"]
        - engineered["scheduled_departure"]
    ).dt.total_seconds().div(60)
    engineered["progress_ratio"] = (
        elapsed_schedule_minutes
        / engineered["scheduled_travel_time_min"].where(
            engineered["scheduled_travel_time_min"].ne(0)
        )
    )
    engineered["progress_ratio"] = (
        pd.to_numeric(engineered["progress_ratio"], errors="coerce")
        .clip(0, 1)
        .fillna(0)
    )
    engineered[TARGET_COLUMN] = (
        engineered["actual_destination_arrival"]
        - engineered["scheduled_destination_arrival"]
    ).dt.total_seconds().div(60).round(2)
    engineered["service_date"] = engineered["service_date"].dt.strftime("%Y-%m-%d")
    return engineered


def _prepare_model_frame(engineered: pd.DataFrame) -> pd.DataFrame:
    model_frame = engineered[FEATURE_COLUMNS + [TARGET_COLUMN, "service_date"]].copy()
    model_frame = pd.get_dummies(
        model_frame,
        columns=[
            "train_id",
            "route_id",
            "section_id",
            "route_section",
            "weather_condition",
            "track_condition",
            "signal_aspect",
        ],
        dtype=int,
    )
    return model_frame


def run_pipeline(input_path: Path, output_dir: Path) -> dict[str, object]:
    raw = pd.read_csv(input_path)
    cleaned, cleaning_summary = _clean(raw)
    engineered = _engineer_features(cleaned)
    model_frame = _prepare_model_frame(engineered)

    model_frame = model_frame.sort_values("service_date").reset_index(drop=True)
    split_index = max(1, int(len(model_frame) * 0.8))
    train = model_frame.iloc[:split_index].copy()
    test = model_frame.iloc[split_index:].copy()

    output_dir.mkdir(parents=True, exist_ok=True)
    engineered.to_csv(output_dir / "eta_features.csv", index=False)
    train.to_csv(output_dir / "train.csv", index=False)
    test.to_csv(output_dir / "test.csv", index=False)

    metadata = {
        "data_source": "Synthetic prototype data generated locally; not real railway data.",
        "raw_input": str(input_path),
        "raw_columns": RAW_COLUMNS,
        "engineered_features": FEATURE_COLUMNS,
        "target": {
            "name": TARGET_COLUMN,
            "definition": "Actual destination arrival minus scheduled destination arrival, in minutes.",
        },
        "cleaning_summary": cleaning_summary,
        "dataset_size": {"cleaned_engineered_rows": len(engineered), "model_columns": len(model_frame.columns)},
        "split": {
            "method": "chronological 80/20 split by service_date",
            "train_rows": len(train),
            "test_rows": len(test),
            "train_date_min": str(train["service_date"].min()),
            "train_date_max": str(train["service_date"].max()),
            "test_date_min": str(test["service_date"].min()),
            "test_date_max": str(test["service_date"].max()),
        },
    }
    (output_dir / "metadata.json").write_text(
        json.dumps(metadata, indent=2), encoding="utf-8"
    )
    return metadata


def main() -> None:
    args = parse_args()
    metadata = run_pipeline(Path(args.input), Path(args.output_dir))
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
